services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  books:
    image: node:15.6
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    ports:
      - 3000:3002
    command: npm run dev
    depends_on:
      - storage
